services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/home/oscar/Documents/DockerPractice/volumes/postgres/data/
    networks:
      - spring-boot-network

  spring-boot-app:
    container_name: spring-first
    image: spring/first
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network

volumes:
  postgres:

networks:
  spring-boot-network:
    driver: bridge